version: '3'
services:
  app:
    networks:
      - backend
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kokodi
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    networks:
      - backend
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d kokodi" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
networks:
 backend:
