spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: ${DB_URL}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

application:
  gameSession:
    winScore: 30
  jwt:
    secret: 25cf3c44c8f39313e8cbf7c23e22fe8b2e4d5288ee5206b0a6397583a1f7f0ef
    accessTokenExpiration: 600000
    refreshTokenExpiration: 3600000
    expiredToken: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJlbWFpbC0xQGdtYWlsLmNvbSIsImlhdCI6MTcyNzQ1Mjk2MCwiZXhwIjoxNzI3NDU2NTYwfQ.oP0dNWn75v8Ka7fvxt-966ug2q3A5i4Ef-urjo0bQtSCZeq9f4ijA7HydBC-xMX2
